<?php

namespace AppBundle\Repository;

/**
 * LoginAttemptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginAttemptRepository extends \Doctrine\ORM\EntityRepository
{
}
