<?php

namespace AppBundle\Repository;

/**
 * RefreshTokenKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshTokenKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
