admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app_api:
    resource: "@AppBundle/Controller"
    type:     annotation

app_api_v1:
    resource: "@AppBundle/Controller/V1"
    type:     annotation
    prefix: /v{version}
    requirements:
      version: '^1$'

app_api_v2:
    resource: "@AppBundle/Controller/V2"
    type:     annotation
    prefix: /v{version}
    requirements:
      version: '^2$'
