admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app_api:
    resource: "@AppBundle/Controller"
    type:     annotation
    prefix: /v{_version}
