security:
    encoders:
        AppBundle\Entity\User:    plaintext

    providers:
        default:
            entity:                 { class: AppBundle:User }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_oauth2_authorize:
            pattern:                ^/api/oauth2/authorize$
            http_basic:             ~
            provider:               default

        api_oauth2_token:
            pattern:                ^/api/oauth2/token$
            oauth2_token:           ~

        api_oauth2_debug:
            pattern:                ^/api/oauth2/debug$
            oauth2_resource:        ~

        api_auth:
            pattern:                ^/api/auth
            oauth2_token:        ~

        api_resource:
            pattern:                ^/api/resource
            oauth2_resource:        ~

        api_resource_model:
            pattern:                ^/api/resource/model$
            oauth2_resource:
                resource_type:      model