security:
    encoders:
        AppBundle\Entity\User:    plaintext

    providers:
        default:
            id: user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        admin_api:
            pattern:    ^/admin
            security:   false

        app_api_public:
            pattern:    ^/v(\d+)/public
            security:   false

        app_api:
            pattern:    ^/v(\d+)
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

    access_control:
        - { path: ^/v(\d+)/public, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/v(\d+),        roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/admin,        roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }