security:
    encoders:
        AppBundle\Entity\User:    plaintext

    providers:
        default:
            id: user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        admin_api:
            pattern: ^/admin/api
            security:   false

        app_api_public:
            pattern: ^/api/public
            security:   false

        app_api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

    access_control:
        - { path: ^/api/public, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api,        roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/admin/api,  roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }