parameters: ~

services:
    user_manager:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getManagerForClass]
        arguments: ["AppBundle:User"]

    user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@user_manager", getRepository]
        arguments: ["AppBundle:User"]

    user_provider:
        class: AppBundle\User\UserProvider
        arguments: ["@user_repository"]
        
    email_service:
        class: AppBundle\Service\EmailService
        arguments:
            - "@mailer"
            - "%mailer_email%"
            - "%mailer_name%"

    sms_service:
        class: AppBundle\Service\SMSService
        arguments: ~

    verification_code_helper:
        class: AppBundle\Helper\VerificationCodeHelper
        arguments:
            - "@doctrine.orm.entity_manager"

    user_helper:
        class: AppBundle\Helper\UserHelper
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@mobile_number_helper"
            - "@email_address_helper"
            - "@user_setting_helper"

    user_setting_helper:
        class: AppBundle\Helper\UserSettingHelper
        arguments:
            - "@doctrine.orm.entity_manager"

    mobile_number_helper:
        class: AppBundle\Helper\MobileNumberHelper
        arguments:
            - "@doctrine.orm.entity_manager"

    email_address_helper:
        class: AppBundle\Helper\EmailAddressHelper
        arguments:
            - "@doctrine.orm.entity_manager"

    app.api_version_listener:
        class: AppBundle\EventListener\ApiVersionListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }
        arguments:
            - "@service_container"

    app.two_factor_auth_listener:
        class: AppBundle\EventListener\TwoFactorAuthListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }
        arguments:
            - "@service_container"

    app.user_registration_listener:
        class: AppBundle\EventListener\UserRegistrationListener
        tags:
            - { name: kernel.event_listener, event: app.user_registration, method: onComplete, priority: -1 }
        arguments:
            - "@service_container"

    app.login_success_listener:
        class: AppBundle\EventListener\UserLoginListener
        tags:
            - { name: kernel.event_listener, event: app.login_success, method: onSuccess, priority: -1 }
        arguments:
            - "@service_container"

    app.login_failure_listener:
        class: AppBundle\EventListener\UserLoginListener
        tags:
            - { name: kernel.event_listener, event: app.login_failure, method: onFailure, priority: -1 }
        arguments:
            - "@service_container"

    app.username_change_listener:
        class: AppBundle\EventListener\UsernameChangeListener
        tags:
            - { name: kernel.event_listener, event: app.username_change, method: onComplete, priority: -1 }
        arguments:
            - "@service_container"

    date_time_normalizer:
        class: AppBundle\Normalizer\DateTimeNormalizer
        tags:
            - { name: serializer.normalizer }