<?php

namespace AppBundle\Entity;

/**
 * MobileNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
