<?php

namespace AppBundle\Entity;

/**
 * VerificationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
